subprojects {
    group = 'jks.tools2d'
    version = rootProject.version

    plugins.withType(JavaPlugin).configureEach {
        tasks.withType(JavaCompile).configureEach {
            options.encoding = 'UTF-8'
            options.compilerArgs += ['-Xlint:deprecation', '-Xlint:unchecked']
        }
        tasks.withType(Test).configureEach {
            useJUnitPlatform()
        }
    }
}
